spring:
  # base de datos en la nube -> Render
  datasource:
    url: jdbc:postgresql://dpg-cpipodsf7o1s73bkq2ng-a.oregon-postgres.render.com/politics_data_j2oj
    username: admin
    password: LWliyFTOMApKkf1zAbIUucuqGNRWp9OO
    driver-class-name: org.postgresql.Driver

# alternativa, usar una base in-memory H2
#  database: H2
#
#  h2:
#    console:
#      enabled: true
#      path: /h2
#
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password: sa
#    driverClassName: org.h2.Driver
#
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always

# Para activar el Trace
logging:
  level:
    root: INFO
