#spring:
  #   base de datos posta
#  datasource:
#      url: jdbc:postgresql://localhost:5432/politics

spring:
  database: H2

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

# Para activar el Trace
logging:
  level:
    root: DEBUG